petshop/core/urls.py
from django.urls import path
from petshop.core.views import home, estoque, agendamento
app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('estoque/', estoque, name='estoque'),
    path('agendamento/', agendamento, name='agendamento'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
admin.autodiscover()
app_name = 'core'

urlpatterns = [
    path('', include('petshop.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

petshop/core/models.py
from django.db import models


class EstoqueManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(nome__icontains=query)
            )


class Estoque(models.Model):
    nome = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    qtd = models.IntegerField(default=0)
    valor = models.DecimalField('Preço', max_digits=5, decimal_places=2)
    start_date = models.DateField(
        'Data de Início', null=True, blank=True
    )
    created_at = models.DateTimeField(
        'Criado em', auto_now_add=True
    )
    updated_at = models.DateTimeField(
        'Atualizado em', auto_now=True
    )

    objects = EstoqueManager()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Estoque'
        verbose_name_plural = 'Estoques'
        ordering = ['nome']

petshop/core/views.py
from django.shortcuts import render
from .models import Estoque


def home(request):
    return render(request, 'home.html')


def estoque(request):
    estoque = Estoque.objects.all()
    template_name = 'estoque.html'
    context = {
        'estoque': estoque
    }
    return render(request, template_name, context)


def agendamento(request):
    return render(request, 'agendamento.html')

petshop/core/templates/agendamento.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div id="main">
    <div class="header">
        <h1 class="titulo">Agendamentos</h1>
        <h2>Agende o atendimento do seu animal</h2>
    </div>

</div>

{% endblock %}

petshop/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Petshop &ndash; Layout &ndash; Pure</title>
        
        <link rel="stylesheet" href="{% static 'css/side-menu.css' %}" />
        
    </head>
    <body>






        <div id="layout">
            <!-- Menu toggle -->
            <a href="#menu" id="menuLink" class="menu-link">
                <!-- Hamburger icon -->
                <span></span>
            </a>

            <div id="menu">
                <div class="pure-menu">
                    <a class="pure-menu-heading" href="#">Company</a>

                    <ul class="pure-menu-list">
                        <li class="pure-menu-item"><a href="{% url 'core:home' %}" class="pure-menu-link">Home</a></li>
                        <li class="pure-menu-item"><a href="{% url 'core:estoque' %}" class="pure-menu-link">Estoque</a></li>

                        <li class="pure-menu-item menu-item-divided pure-menu-selected">
                            <a href="{% url 'core:agendamento' %}" class="pure-menu-link">Agendamento</a>
                        </li>

                        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Contact</a></li>
                    </ul>
                </div>
            </div>
            {% block content%}{% endblock %}
        </div>
        <script src="{% static 'js/ui.js' %}"></script>
    </body>
</html>

petshop/core/templates/estoque.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div id="main">
    <div class="header">
        <h1>Estoque</h1>
        <h2>Controle de Estoque</h2>
    </div>
    {% for item in estoque %}
    <div class="content">
        <div class="lista">
            <span title="{{ item.pk }}">Codigo: {{ item.pk }}</span>
        </div>
        <div>
            <a>Nome do Produto: {{ item.nome }}</a>            
        </div>
        <div>
            <a> Quantidade: {{ item.qtd }}</a><span>   -   </span>
            <a>Valor: {{ item.valor }}</a><span>   -   </span>
            <a></a>
        </div>
        <hr>
    </div>
    {% empty %}
    <span>Não existe item no banco!</span>
</div>

{% endfor %}
{% endblock %}

petshop/core/templates/home.html
{% extends "base.html" %}

{% block content %}

<div id="main">
    <div class="header">
        <h1>Petshop</h1>
        <h2>A subtitle for your page goes here</h2>
    </div>

    <div class="content">
        <h2 class="content-subhead">How to use this layout</h2>
        <p>
            Mussum Ipsum, cacilds vidis litro abertis. Si num tem leite então bota uma pinga aí cumpadi! Quem manda na minha terra sou euzis! Manduma pindureta quium dia nois paga. Casamentiss faiz malandris se pirulitá.

Interagi no mé, cursus quis, vehicula ac nisi. Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. Sapien in monti palavris qui num significa nadis i pareci latim.

Praesent vel viverra nisi. Mauris aliquet nunc non turpis scelerisque, eget. Copo furadis é disculpa de bebadis, arcu quam euismod magna. Suco de cevadiss deixa as pessoas mais interessantis. Mais vale um bebadis conhecidiss, que um alcoolatra anonimis.

Não sou faixa preta cumpadi, sou preto inteiris, inteiris. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Quem num gosta di mé, boa gentis num é. Per aumento de cachacis, eu reclamis.

Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis. Aenean aliquam molestie leo, vitae iaculis nisl. Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo! In elementis mé pra quem é amistosis quis leo.
        </p>

        <h2 class="content-subhead">Now Let's Speak Some Latin</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>

        <div class="pure-g">
            <div class="pure-u-1-4">
                <img class="pure-img-responsive" src="http://farm3.staticflickr.com/2875/9069037713_1752f5daeb.jpg" alt="Peyto Lake">
            </div>
            <div class="pure-u-1-4">
                <img class="pure-img-responsive" src="http://farm3.staticflickr.com/2813/9069585985_80da8db54f.jpg" alt="Train">
            </div>
            <div class="pure-u-1-4">
                <img class="pure-img-responsive" src="http://farm6.staticflickr.com/5456/9121446012_c1640e42d0.jpg" alt="T-Shirt Store">
            </div>
            <div class="pure-u-1-4">
                <img class="pure-img-responsive" src="http://farm8.staticflickr.com/7357/9086701425_fda3024927.jpg" alt="Mountain">
            </div>
        </div>

        <h2 class="content-subhead">Try Resizing your Browser</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </div>
</div>
{% endblock %}



   